main: sb.customplugin.customplugin.CustomPlugin
name: CustomPlugin
version: "${VERSION}"
api-version: "1.16"
author: sbeve and ThiccDecon
description: Custom plugin for this server.
commands:
  debug:
    description: bruh moment
    permission: custom.debug